### ISSUE TITLE
potential GPU performance overhead

### ISSUE THREAD

**Issue by NinaOmejc** [lcdm-uiuc/PyIF#6]
Dear all,
thank you for this implementation, it's very useful. I started to use the GPU version, it works, but I get this warning:

```
NumbaPerformanceWarning: Host array used in CUDA kernel will incur copy overhead to/from device.
  warn(NumbaPerformanceWarning(msg))
```

Is this my potential misuse or setting mistake, or have you also observed this warning?

Thank you.
Kind regards

**Comment by ProfessorBrunner** [comment]
Sorry, this codebase is no longer actively developed or monitored. In my experience, however, I have not seen this warning. That said, perhaps it is not a problem as it implies the performance will take a hit since there will be an additional data copy overhead.
